### ISSUE TITLE
compilation on summitdev

### ISSUE THREAD

**Issue by stevengottlieb** [lattice/quda#595] opened 2017-03-23 21:14 UTC
I am trying to compile on summitdev at ORNL.  Running into a little problem.  The compiler seems to have its own convention for using C++ 11 standard.

I see these warning and errors:

/ccs/home/gottlieb/quda/lib/dirac_coarse.cpp:9:11: error: use of undeclared iden
tifier 'nullptr'
      Y_h(nullptr), X_h(nullptr), Xinv_h(nullptr), Yhat_h(nullptr),

/ccs/home/gottlieb/quda/include/lattice_field.h:384:21: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
  template <typename... Args>

I tried to google for easiest way to add to CFLAGS, but could not figure out how to do it.  

Here is some information about compilers;

-bash-4.2$  which cc
/sw/summitdev/xl/20161123/xlC/13.1.5/bin/cc
-bash-4.2$ cc -v
exec: export(export,XL_CONFIG=/sw/summitdev/xl/20170109/xlC/13.1.5/etc/xlc.cfg.rhel.7.3.gcc.4.8.5.cuda.8.0:cc,NULL) 
/sw/summitdev/xl/20170109/xlC/13.1.5/bin/.orig/cc: error: 1501-294 No input file specified. Please use -qhelp for more information.
unlink: /tmp/xlcW0Tds9AM
unlink: /tmp/xlcW1yhICpZ
unlink: /tmp/xlcW2o5W5dc
-bash-4.2$ which gcc
/usr/bin/gcc

-bash-4.2$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
-bash-4.2$ 

looks like xlC is the compiler from digging into make.build in 
/ccs/home/gottlieb/build/lib/CMakeFiles/quda_cpp.dir

Happy to send any more needed information.

**Comment by maddyscientist** [comment] 2017-03-23 21:17
You need to build with gcc and not with xlC.  I've done this on Minsky systems, and it has worked fine.

@bjoo you've compiled on these systems, any advice for @stevengottlieb?

**Comment by mathiaswagner** [comment] 2017-03-23 21:18
gcc should be fine. The IBM recommendation is gcc 5.4.

**Comment by mathiaswagner** [comment] 2017-03-23 21:19
Out of curiosity: I assume you used cmake. In the first run of cmake (in the clean build dir) the compiler id should be reported. What does it say?

**Comment by mathiaswagner** [comment] 2017-03-23 21:37
Also can you check whether changing the line
`set(CMAKE_CXX_STANDARD_REQUIRED 11)` on the top of QUDA's top level dir's CMakeLists.txt to `set(CMAKE_CXX_STANDARD_REQUIRED ON)` changes anything?

**Comment by cpviolator** [comment] 2017-03-23 21:43
@stevengottlieb Do you have access to an xlc++ compiler?

**Comment by mathiaswagner** [comment] 2017-03-23 21:53
Ok. I think I found the cause for xlc.
According to https://cmake.org/cmake/help/v3.8/manual/cmake-compile-features.7.html#supported-compilers
it is not a compiler that cmake knows the option for and we rely on cmake handling that. The workaround is probably to specify that flag in the CMAKE_CXX_FLAGS which you can modify with ccmake. Also make VERBOSE=1 will print the calls to the compiler and you can check whether it was picked up.

**Comment by stevengottlieb** [comment] 2017-03-24 03:01
@maddyscientist
I added this before the cmake command:
export CC=gcc
export CXX=g++
and make seems to be proceeding smoothly.

What are Minsky systems?

These are the compilers found with this cmake command:
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works

**Comment by maddyscientist** [comment] 2017-03-24 03:03
Minsky is just the name of the IBM platform that comprises SummitDev (POWER8 + 4x P100).

**Comment by junlizhang** [comment] 2017-04-03 11:34
You can just try to use gnu compiler, for example:
  git clone https://github.com/lattice/quda.git && \
  cd quda && \
  mkdir build && \
  cd build && \
  sed -i.ori 's:set(CPU_ARCH x86_64):set(CPU_ARCH ppc64le):g' ../CMakeLists.txt && \
  cmake3 .. \
  -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
  -DCMAKE_C_COMPILER=/usr/bin/gcc \
  -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx \
  -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc \
  -DCUDA_HOST_COMPILER=/usr/bin/g++ \
  -DQUDA_GPU_ARCH=sm_60 \
  -DQUDA_MPI=ON \
  -DCUDA_SDK_ROOT_DIR=/usr/local/cuda \
  -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
  -DQUDA_NUMA_NVML=on \
  -DNVML_LIBRARY=/usr/local/cuda-8.0/targets/ppc64le-linux/lib/stubs/libnvidia-ml.so \
  -DNVML_INCLUDE_DIR=/usr/local/cuda-8.0/targets/ppc64le-linux/include \
  -DCUDA_VERBOSE_BUILD=on \
  -DCMAKE_VERBOSE_MAKEFILE=on \
  -DCMAKE_INSTALL_PREFIX=/usr/local/quda && \
  make -j24 && \
  make install

**Comment by forandom** [comment] 2017-04-11 14:46
For IBM xlC, please try adding -std=c++11 to CXXFLAGS.

**Comment by maddyscientist** [comment] 2017-05-06 18:31
Closing this issue, as I understand this is no longer a problem

**Closed by maddyscientist** 2017-05-06 18:31 UTC
