### ISSUE TITLE
Heavy memory burden on reduce.cu?

### ISSUE THREAD

**Issue by cpviolator** [lattice/quda#522] opened 2016-10-29 05:44 UTC
I'm posting this as a question rather that a bug because it's an issue related to a particular system (Stampede) that has arisen in the past few weeks.

I was working on the development brach pulled on the 22nd of September and I had no issues with compilation. I recently gave instructions to colleagues about how to add additions to QUDA, and instructed them to simply pull the most recent development commit and add the changes. However, I found that when I tested this myself, QUDA threw the error:

`std::bad_alloc()`

during compilation, indicating that the make process had ran out of memory. The offending kernel is reduce_quda.o. I just want to ask if this kernel has recently (since 22nd Sep) had any revisions that would inflate the memory burden. Like I say, this issue is related only to Stampede as I can successfully compile the more recent QUDA commits other systems (nvscocial.) I even tried making with just one core to ensure all available memory was given to one job at a time, but this fails too.

On Stampede, the version I pulled from 22nd of September compiles OK, with and without the additions. Recent versions, with and without additions, fail to compile throwing the above error. Right now I'm compiling QUDA commits one by one to see where the compilation fails in order to pin the specific commit, and I'll report back with findings. Any clues would be appreciated.

**Comment by maddyscientist** [comment] 2016-10-29 06:10
Hmmm, what version of CUDA is on stampede? Does have particularly low memory?  @bjoo I recall you've had memory issues before with compilation though I recall this was related to scratch storage the compiler uses?

**Comment by cpviolator** [comment] 2016-10-30 23:51
On Stampede I use CUDA 7.5, gcc 4.9.3 and mvapich 2.1. Here's a rundown of the builds I tried using a core to make, with the results:

```
howarth@Stampede-/work/03653/howarth/MEM_BUG$ tail -n 6 quda-*/build/log*
==> quda-06da5f9c8206e908376c8b381329c2b67c3e2a95/build/loggy.log <==
  /work/03653/howarth/MEM_BUG/quda-06da5f9c8206e908376c8b381329c2b67c3e2a95/build/lib/CMakeFiles/quda.dir//./quda_generated_reduce_quda.cu.o


make[2]: *** [lib/CMakeFiles/quda.dir/quda_generated_reduce_quda.cu.o] Error 1
make[1]: *** [lib/CMakeFiles/quda.dir/all] Error 2
make: *** [all] Error 2

==> quda-127153033a85cf03f8b7f5f9785933807c662282/build/loggy.log <==
Linking CXX executable staggered_invert_test
[ 98%] Built target staggered_invert_test
Scanning dependencies of target su3_test
[100%] Building CXX object tests/CMakeFiles/su3_test.dir/su3_test.cpp.o
Linking CXX executable su3_test
[100%] Built target su3_test

==> quda-24cf95ec3d00585285d214ece4c22f585933b674/build/loggy.log <==
Linking CXX executable staggered_invert_test
[ 98%] Built target staggered_invert_test
Scanning dependencies of target su3_test
[100%] Building CXX object tests/CMakeFiles/su3_test.dir/su3_test.cpp.o
Linking CXX executable su3_test
[100%] Built target su3_test

==> quda-582e8b2131c5a5df030237cd7c2485b2a05b8ea1/build/loggy.log <==
  /work/03653/howarth/MEM_BUG/quda-582e8b2131c5a5df030237cd7c2485b2a05b8ea1/build/lib/CMakeFiles/quda.dir//./quda_generated_reduce_quda.cu.o


make[2]: *** [lib/CMakeFiles/quda.dir/quda_generated_reduce_quda.cu.o] Error 1
make[1]: *** [lib/CMakeFiles/quda.dir/all] Error 2
make: *** [all] Error 2

==> quda-6f324e66ccda19c43bca1af2ab3d2cc07ea2674f/build/loggy.log <==
Linking CXX executable staggered_invert_test
[ 98%] Built target staggered_invert_test
Scanning dependencies of target su3_test
[100%] Building CXX object tests/CMakeFiles/su3_test.dir/su3_test.cpp.o
Linking CXX executable su3_test
[100%] Built target su3_test

==> quda-ad2114c2c2459c73be901d2c6deac80a0505f437/build/loggy.log <==
  /work/03653/howarth/MEM_BUG/quda-ad2114c2c2459c73be901d2c6deac80a0505f437/build/lib/CMakeFiles/quda.dir//./quda_generated_reduce_quda.cu.o


make[2]: *** [lib/CMakeFiles/quda.dir/quda_generated_reduce_quda.cu.o] Error 1
make[1]: *** [lib/CMakeFiles/quda.dir/all] Error 2
make: *** [all] Error 2
```
All the builds that fail seem to fail on reduce_quda.o Here are the dates of commits:

`6f324e6` Sep 20th: success
`ad2114c2` Sep 22nd: fail
`06da5f9` Sep 23rd: fail
`24cf95e` Sep 26th: success
`1271530` Sep 27th: success
`582e8b2` Oct 17th: fail

So it's a bit of a mixed bag. Not sure what to make of it. I guess I can use a working build on Stampede and perhaps try to replicate these results at a later date. If the build results differ, it's probably just an issue with the available memory on the login nodes. Though I have found that the latest commit `582e8b2` has consistently failed on Stampede.

**Comment by maddyscientist** [comment] 2016-10-31 00:10
Can you try with configure build to rule out a cmake issue?

My cycles are extremely limited for the next few weeks but hopefully we can clear this up.

One other thing to try: try the feature/bicgstab-l branch.  There the multi reductions are in their own file so the compile burden is spread out a bit better.

**Comment by maddyscientist** [comment] 2017-02-20 01:09
@cpviolator just checking: is this an issue?

**Comment by cpviolator** [comment] 2017-02-20 01:11
@maddyscientist It looks like this was a bit of a Heisenbug because I'm not having any issues with newer (2017) builds.

**Comment by maddyscientist** [comment] 2017-02-20 01:28
Ok, I'll close the issue then.  Could have been caused by the reductions and ,unto reductions being in the same file as I noted above, something which has since been resolved.

**Closed by maddyscientist** 2017-02-20 01:28 UTC
Labels: question
