### ISSUE TITLE
cuda-6.5 issue 

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#299] opened 2015-06-26 15:43 UTC
compilation for the latest develop branch fails when I tried CUDA-6.5. (CUDA-7.0 worked fine.) Compiler output
/usr/local/cuda-6.5/bin/nvcc  -O3 -D__COMPUTE_CAPABILITY__=350 -ftz=true -prec-div=false -prec-sqrt=false  -w -DMULTI_GPU -DDYNAMIC_CLOVER -DGPU_WILSON_DIRAC -DGPU_CLOVER_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC -DGPU_TWISTED_CLOVER_DIRAC -DGPU_CLOVER_DIRAC -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC -DGPU_GAUGE_TOOLS -DGPU_DIRECT -DBUILD_QDP_INTERFACE -DDEVICE_PACK -DNUMA_AFFINITY -arch=sm_35         -I/usr/local/cuda-6.5/include -DHAVE_QIO -I/lqcdproj/astrel/install/scidac-gcc-4.8.4-ompi-1.8.1/qio/include -DQMP_COMMS -I/lqcdproj/astrel/install/scidac-gcc-4.8.4-ompi-1.8.1/qmp/include -I../include -Idslash_core -I.  dslash_pack.cu -c -o dslash_pack.o
ptxas /tmp/tmpxft_00004a70_00000000-5_dslash_twisted_clover.ptx, line 295466; fatal   : Parsing error near '�': syntax error
ptxas <macro util>, line 9; error   : Arguments mismatch for instruction 'mov'

Could anyone confirm?

**Comment by AlexVaq** [comment] 2015-06-26 16:02
For me it happened a few times that astray characters (might be indistinguisable from a space) spoilt compilation. I suppose this is not the case, but did you try to check?

**Comment by mathiaswagner** [comment] 2015-06-26 16:23
Can you share your `make.inc` ?
Do you have any idea which configuration option might trigger the error?

**Comment by mikeaclark** [comment] 2015-06-26 16:49
This is a CUDA 6.5 bug.  It was fixed with 7.0.  I tried to work around it for the 0.7.0 release (look for the mysterious char inserted into DslashParam), but it is extremely brittle and can break again if an other parameter is added to the struct.

I was planning on rewriting the DslashParam struct at some point such that it uses derived classes for each DslashType, similar to DslashCuda, its children. This could help provide a work around for this, or at least make the solution less brittle.

This doesn't help immediately for Titan though.  A workaround in the meantime may be found by enabling more dirac operators (staggered/domain wall).

**Comment by alexstrel** [comment] 2015-06-26 17:12
for me this happened with twisted-clover (+dynamic clover inversion), when disabled then compilation works

**Comment by mikeaclark** [comment] 2015-06-26 17:36
Is it still broken if you enable all fermion types?

**Comment by AlexVaq** [comment] 2015-06-26 17:48
I should stop using my mac to edit the files. It's really easy to insert those rogue characters, and then it's almost impossible to find them.

I might try later with an hex-editor.

**Comment by mikeaclark** [comment] 2015-06-26 17:52
I don't think this is a file editing problem, this is a bug in CUDA 6.5.  If you look at the ptx files generated, in some case the characters produced are Mandarin Chinese (no joke!)

**Comment by alexstrel** [comment] 2015-06-26 18:02
cuda-6.5 works properly at least with Wilson, Wlson-Clover and Twisted mass (degenerate flavors)

**Comment by mikeaclark** [comment] 2015-06-26 18:06
It's possible this bug was triggered by a rogue character though, I never considered that.  It would be good to pin this down if that's the case.

Alex, I did notice that some of the contraction code did have rogue ^M characters.

**Comment by alexstrel** [comment] 2015-06-26 18:10
so looks like cuda-7.0 can swallow them all without complaints

**Comment by mathiaswagner** [comment] 2015-06-26 19:28
Just to make sure as Titan and BlueWaters are now CUDA 6.5 by default: Is this bug also present in the release branch?

**Comment by AlexVaq** [comment] 2015-06-26 19:54
In my mac sometimes I can't execute properly bash commanda because I introduce rogue characters if I'm writting fast (like I press the spacebar withouy releasing alt). That's why I think that, whenever I edit stuff from the mac, I might be causing mayhem... :S

**Comment by AlexVaq** [comment] 2015-06-26 19:55
Also, the fact that Alexei has problems only with my code makes me think I did something...

**Comment by mikeaclark** [comment] 2015-06-26 20:24
I wonder if there is an automated tool we could use to search for these characters?

**Comment by AlexVaq** [comment] 2015-06-26 20:34
Maybe I can write some code...

**Comment by mathiaswagner** [comment] 2015-06-27 01:42
I am pretty sure that you don't have to write that yourself. But I didn't ask google yet.

**Comment by mathiaswagner** [comment] 2015-06-27 02:31
@Alexvaq: http://superuser.com/questions/78245/how-to-disable-the-option-space-key-combination-for-non-breaking-spaces might solve your issues

**Comment by AlexVaq** [comment] 2015-06-27 07:40
That's GREAT! Thanks!!

**Comment by mathiaswagner** [comment] 2015-07-07 00:15
Where do we stand on this?

**Comment by nmrcardoso** [comment] 2015-07-23 22:07
This kind of problem also happens with file  extract_gauge_ghost.cu and cuda 6.5
ptxas /tmp/tmpxft_00001777_00000000-5_extract_gauge_ghost.ptx, line 2553; fatal   : Parsing error near '�': syntax error
ptxas <macro util>, line 10; error   : Arguments mismatch for instruction 'mov

**Comment by mikeaclark** [comment] 2015-07-23 22:09
@nmrcardoso, I presume it doesn't happen with CUDA 7.0, only 6.5?

**Comment by nmrcardoso** [comment] 2015-07-23 22:13
yes, only with cuda 6.5.
The removal of non-breaking spaces fixed the problem?
if yes, there is a script for this?

**Comment by nmrcardoso** [comment] 2015-07-23 23:03
Looking at the ptx file, there is many ld.param.u64 entries like this one:
ld.param.u64 %rd258, [ Ìª X +128];

**Comment by nmrcardoso** [comment] 2015-07-23 23:07
the problem is at gauge_field_order.h file.
Don't know yet where in this file.

**Comment by mikeaclark** [comment] 2015-07-23 23:16
Does this help?
http://stackoverflow.com/questions/12999651/how-to-remove-non-utf-8-characters-from-text-file

**Comment by nmrcardoso** [comment] 2015-07-23 23:27
@mike, that didn't help me.
At least I have now pretty sure that the problem is inside this function on
that file:
__device__ __host__ inline void saveGhost(const RegType v[length], int x,
int dir, int parity)

probably this is the same problem dslash_twisted_clover file but for the
clover order... that Alexei had reported some time ago...

Now I have to leave, but later I will try to look better this function or
rewrite it...

**Comment by mikeaclark** [comment] 2015-07-23 23:29
In the feature/gauge-fix branch I've found a series of ^M characters in
* include/random.h
* lib/covDev.h
* lib/dslash_core/contract_core.h
* lib/dslash_core/contract_core_minus.h
* lib/dslash_core/contract_core_plus.h
* lib/generate/deg_tm_dslash_cuda_gen.py
* lib/generate/deg_tmc_dslash_cuda_gen.py
* lib/generate/dslash_cuda_gen.py
* lib/generate/fused_exterior_deg_tm_dslash_cuda_gen.py
* lib/generate/fused_exterior_deg_tmc_dslash_cuda_gen.py
* lib/generate/fused_exterior_dslash_gen.py
* lib/generate/fused_exterior_ndeg_tm_dslash_cuda_gen.py
* lib/generate/ndeg_tm_dslash_cuda_gen.py
* lib/random.cu
But none in gauge_field_order.h.

**Comment by mikeaclark** [comment] 2015-07-23 23:32
I found a nice utility to get rid of these characters [dos2unix] (http://www.liquidweb.com/kb/dos2unix-removing-hidden-windows-characters-from-files/).  Can you try running that on all files in your director, e.g.
```
dos2unix * */* */*/*
```
and see if that helps the problem.

There was an issue in the CUDA 6.5 compiler, so the character issue may not be the problem.

**Comment by nmrcardoso** [comment] 2015-07-24 01:16
@mike, the command did not worked for me, probably because I'm using linux?

Nevertheless, I think I found a workaround, at least no more that strange
error.
Solution was changing the order in two lines in gauge_field_order.h on
template <typename Float, int length, int N, int reconLen>
    struct FloatNOrder {
from
      int faceVolumeCB[4];
      const int volumeCB;
to
      const int volumeCB;
      int faceVolumeCB[4];

This is kind odd.

**Comment by AlexVaq** [comment] 2015-07-24 05:34
That was me and my mac...

**Comment by mikeaclark** [comment] 2015-07-24 06:32
@nmrcardoso, I used the utility on linux :)

Was this problem seen on feature/gauge-fix branch?  If so, can you push the fix there before we merge this?  thx

**Comment by mathiaswagner** [comment] 2015-07-24 10:47
For the Mac users: TextWrangler (free, either on the Appstore or at http://www.barebones.com/products/textwrangler/) has a function *Zap Gremlins* which should get rid off all these problematic characters.

I am wondering whether you can configure git to preprocess (run the dos2unix tool ?) the source before committing.

**Comment by nmrcardoso** [comment] 2015-07-24 15:48
@mikeaclark, yes I saw this problem in feature/gauge-fix branch.
I added the fix.

**Comment by mathiaswagner** [comment] 2015-10-22 08:26
@alexstrel @nmrcardoso @AlexVaq : Does anyone of you still have issues? All my recent builds with Cuda 6.5 did not suffer from this. 
If I don't get any replies that we still have problems here I will close this issue.

**Comment by nmrcardoso** [comment] 2015-10-22 11:11
I only had issues with cuda 6.5 on tegra, otherwise it worked fine with the above fix in the FloatNOrder struct. But since anyone will be using quda in tegra systems,arm, you can close this.

**Comment by mathiaswagner** [comment] 2015-10-26 12:46
Looks like this is currently no longer an issue.

**Closed by mathiaswagner** 2015-10-26 12:46 UTC
Labels: bug
