### ISSUE TITLE
develop branch broken by blas_magma.cpp

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#334] opened 2015-07-30 20:39 UTC
Problem with blas_magma.cpp file:
magma functions called outside  #ifdef MAGMA_LIB ... #endif

**Comment by mikeaclark** [comment] 2015-07-30 20:45
Thanks @nmrcardoso.  Closing this issue, it is a duplicate of #335 that I just filed (more detail is on that bug).

**Closed by mikeaclark** 2015-07-30 20:45 UTC
Labels: bug

**Comment by alexstrel** [comment] 2015-07-30 21:06
Thanks for brinning my attention! Creating hotfix branch for the issue. 
@mikeaclark  C99 notations is unavoidable if one uses Lapack C interface( as it is in the current implementation), isn't it?
