### ISSUE TITLE
Compilation fails for Fermi, CUDA 5.5

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#404] opened 2015-12-03 10:10 UTC
During compilation in a local cluster in Cyprus using Fermi I came accross with this error:

make[1]: se ingresa al directorio `/fhgfs/prometheus/home/avaquero/git/test/quda-develop/lib'
/fhgfs/prometheus/buildsets/eb141014/software/CUDA/5.5.22/bin/nvcc  -O3 -D__COMPUTE_CAPABILITY__=200 -ftz=true -prec-div=false -prec-sqrt=false  -w -DMULTI_GPU -DPTHREADS -DGPU_WILSON_DIRAC -DGPU_TWISTED_MASS_DIRAC -DGPU_WILSON_DIRAC -g -DHOST_DEBUG -DBUILD_QDP_INTERFACE -DDEVICE_PACK -DGPU_CONTRACT -arch=sm_20                        -I/fhgfs/prometheus/buildsets/eb141014/software/CUDA/5.5.22/include -DMPI_COMMS  -I/include -I../include -Idslash_core -I.  dslash_wilson.cu -c -o dslash_wilson.o
./dslash_policy.cuh(120): error: identifier "aux_worker" is undefined

aux_worker is defined in the namespace dslash, inside dslash_quda.cu line 111. It's also included in the small file dslash_events.cuh as an extern variable. Somehow the compiler seems not to understand that we should be using namespace dslash.

These are the versions I'm using of CUDA, gcc and MPI:

Currently Loaded Modules:
  1) CUDA/5.5.22   2) MVAPICH2/1.9-GCC-4.7.3   3) GCC/4.7.3

**Comment by mathiaswagner** [comment] 2015-12-03 10:23
Development branch or release?

**Comment by AlexVaq** [comment] 2015-12-03 10:28
Development

**Comment by AlexVaq** [comment] 2015-12-03 10:30
Adding:

using namespace dslash;

in line 114 of  dslash_policy.cuh seems to do the trick, but I'm sure this is not a very good solution.

**Comment by mathiaswagner** [comment] 2015-12-03 10:37
Have you tried different builds (different CUDA, release, without HOST_DEBUG) ?

**Comment by AlexVaq** [comment] 2015-12-03 10:41
No, I didn't. It's very possible that the issue is pretty restricted to a very specific configuration. I never had this problem before.

**Comment by AlexVaq** [comment] 2015-12-03 11:00
I confirm that the bug persists if HOST_DEBUG is set to "no".

**Comment by mathiaswagner** [comment] 2015-12-04 09:54
Not sure whether this is an option on the system: Have you tried newer CUDA versions? (If you install CUDA in your home you can still use it to test compilation but the created binary might not run because of a too old cuda driver).

**Comment by AlexVaq** [comment] 2015-12-04 10:20
I can try CUDA 6.0.37, but if I remember well, CUDA 6 was plagued with issues, so I don't know if that would give us new info or make things worse.

**Comment by maddyscientist** [comment] 2015-12-07 14:44
I'll try to find a workaround.  Is there any reason why this machine is still using 5.5? I would have hoped that we don't have to support such an old version.

**Comment by AlexVaq** [comment] 2015-12-09 09:55
Sorry for the late reply, Kate. Here we had long holidays.

This machine is a cypriot machine that is not decomissioned because it's almost the best they have, and the alternative version is CUDA 6.0.37. If you think it might help, I'll recompile for that version and see if the error persist.

But it is really stupid. I mean, it is not a CUDA issue, it looks like a c++ issue (maybe related to nvcc). And the workaround is really simple. But I agree it shouldn't happen. Mostly if we explicitly say that we still support Fermi and CUDA 5.5.

**Comment by AlexVaq** [comment] 2015-12-09 09:56
Alternatively, we can drop support for 5.5 in the next release. Looks like a drastic way of solving problems, but I agree we shouldn't be burden with legacy code.

**Comment by maddyscientist** [comment] 2015-12-09 16:55
I cannot reproduce this issue.  I'm using CUDA 5.5 and GCC 4.7.3, and yet compilation is working fine for me.  I've also tried CUDA 7.5 with GCC 4.7.3, and CUDA 5.5 with GCC 4.8.4.

**Comment by AlexVaq** [comment] 2015-12-09 17:12
Mmm, then it might be related to the cupriot machine. Actually today we compiled in a different machine wthout issues.

I suppose we can close this issue.

**Comment by maddyscientist** [comment] 2015-12-09 17:22
Ok, closing this issue for now.  If you understand how to reproduce it then we can reinvestigate then.

**Closed by maddyscientist** 2015-12-09 17:22 UTC
Labels: bug
