### ISSUE TITLE
The current QUDA/develop fails to compile on Summit

### ISSUE THREAD

**Issue by detar** [lattice/quda#881] opened 2019-08-24 20:36 UTC
With the latest develop version, the compiler chokes on multi_blas_helper.cuh

Using modules

Currently Loaded Modules:
  1) hsi/5.0.2.p5            5) DefApps                          9) cuda/10.1.168
  2) xalt/1.1.3              6) gcc/6.4.0                       10) fftw/3.3.8
  3) lsf-tools/2.0           7) cmake/3.15.2
  4) darshan-runtime/3.1.7   8) spectrum-mpi/10.3.0.1-20190611

Is a higher version of gcc required?   Is a higher version of C++ required?

Here is a sample error message:

/ccs/home/detar/quda/include/multi_blas_helper.cuh(74): error: statement may not appear in a constexpr function
          detected during:
            instantiation of "void quda::blas::multiBlas<NXZ_,RegType,StoreType,yType,M,Functor,write,T>(const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, std::vector<quda::ColorSpinorField *, std::allocator<quda::ColorSpinorField *>> &, std::vector<quda::ColorSpinorField *, std::allocator<quda::ColorSpinorField *>> &, std::vector<quda::ColorSpinorField *, std::allocator<quda::ColorSpinorField *>> &, std::vector<quda::ColorSpinorField *, std::allocator<quda::ColorSpinorField *>> &, int) [with NXZ_=1, RegType=double2, StoreType=float4, yType=double2, M=12, Functor=quda::blas::multicaxpy_, write=quda::blas::write<0, 1, 0, 0>, T=quda::Complex]" 
/ccs/home/detar/quda/lib/multi_blas_quda.cu(428): here
            instantiation of "void quda::blas::mixedMultiBlas<NXZ,Functor,write,T>(const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &) [with NXZ=1, Functor=quda::blas::multicaxpy_, write=quda::blas::write<0, 1, 0, 0>, T=quda::Complex]" 
/ccs/home/detar/quda/lib/multi_blas_quda.cu(554): here
            instantiation of "void quda::blas::multiBlas<NXZ,Functor,write,T>(const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &) [with NXZ=1, Functor=quda::blas::multicaxpy_, write=quda::blas::write<0, 1, 0, 0>, T=quda::Complex]" 
/ccs/home/detar/quda/lib/multi_blas_quda.cu(568): here
            instantiation of "void quda::blas::multiBlas<Functor,write,T>(const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, const quda::blas::coeff_array<T> &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &, quda::CompositeColorSpinorField &) [with Functor=quda::blas::multicaxpy_, write=quda::blas::write<0, 1, 0, 0>, T=quda::Complex]" 
/ccs/home/detar/quda/lib/multi_blas_quda.cu(699): here
            instantiation of "void quda::blas::axpy_recurse<Functor,T>(const T *, std::vector<quda::ColorSpinorField *, std::allocator<quda::ColorSpinorField *>> &, std::vector<quda::ColorSpinorField *, std::allocator<quda::ColorSpinorField *>> &, int, int, int) [with Functor=quda::blas::multicaxpy_, T=quda::Complex]" 
/ccs/home/detar/quda/lib/multi_blas_quda.cu(717): here

There were many similar messages.

Thanks,
Carleton

**Comment by cpviolator** [comment] 2019-08-24 20:43
Did you pull the latest commits from develop, then recompile? I saw this issue once and thought I'd made an error, so deleted the source code and downloaded a fresh copy of develop branch. That solved the issue.

May I ask that, if you've not already done so, you download a fresh copy of QUDA and recompile? Please keep that buggy version though, this is clearly a real bug that needs to be fixed.

**Comment by maddyscientist** [comment] 2019-08-24 20:56
Hi @detar.  I’ve seen this issue before, whence it was caused by bugs in older gcc.  I see that you’ve loaded up gcc 6.4, but I wonder if an old version is being used by CUDA for the .cu files.  Can you paste the output from compiling with `make VERBOSE=1`, which will allow us to see the full command invoked?

**Comment by maddyscientist** [comment] 2019-08-25 06:28
I can't reproduce this issue with gcc 5, and things compile fine, so that's not the issue.

Looking at the error message, I think I know what the problem is: I think you've reused a prior build and updated the source code without rerunning cmake.  QUDA now requires to be built with C++14, so if you reuse a prior cmake generated makefile, it will try to build with C++11, and give you that error (C++14 has much more flexible `constexpr` functionality, which we now utilize in QUDA).

**Comment by mathiaswagner** [comment] 2019-08-25 16:10
I think rerunning cmake alone won’t fix that. It doesn’t overwrite the cxx_standard in the cache. Either fresh build Dir or setting QUDA_CXX_STANDARD to 14 should do.

**Comment by detar** [comment] 2019-08-25 20:09
Hmm.  I did rerun cmake to be sure -- wiped the build directory and 
started from my old CMakeCache.txt.  I also looked for options that 
specified the version of C++ in the ccmake selections and in the 
Makefile that was generated -- I didn't see any.  But I'll find a way to 
force the issue, based on your observation.

Thanks,

Carleton

**Comment by maddyscientist** [comment] 2019-08-25 20:54
Hi Carleton.  You need to either create a new CMakeCache.txt file from fresh or explicitly reset the QUDA_CXX_STANDARD to be 14.

**Comment by detar** [comment] 2019-08-25 22:09
Thanks, everyone, for the advice.  Earlier this afternoon, I found the 
QUDA_CXX_STANDARD option in the advanced cmake set.  I also switched to 
gcc-7.4.0.  The build, still underway, has passed the previous failure 
point.

Best,

Carleton

**Comment by cpviolator** [comment] 2019-09-05 17:36
@detar How did this pan out? Everything OK?

**Comment by maddyscientist** [comment] 2019-09-20 02:22
Closing this issue, since it has been resolved.

**Closed by maddyscientist** 2019-09-20 02:22 UTC
