### ISSUE TITLE
Possible bug in twisted-mass nondeg for half precision

### ISSUE THREAD

**Issue by AlexVaq** [lattice/quda#611] opened 2017-04-18 20:09 UTC
@alexstrel can you check line 961 of tm_core.h?

float a = param.a_f
float b = param.b_f
float c = param.b_f

I guess the third sould be

float c = param.c_f

Am I missing something?

**Comment by maddyscientist** [comment] 2017-04-18 20:10
Does it give the wrong answer that is fixed by correcting this?

**Comment by AlexVaq** [comment] 2017-04-18 20:15
I didn't test. I know I should but I'm terribly overworked. I found this while trying to debug the nondeg twisted clover.

**Comment by maddyscientist** [comment] 2017-04-19 06:28
I've confirmed this is a bug, with the obvious fix being the correct thing to do.  Doing more testing of the non-degenerate twisted-mass fermions has revealed further issued, such as the unit tests not being fully implemented for this operator for some reason, e.g., we can solver for Mx=b using CGNR, but we can't solve for M*M x = b.  

Moreover, there seems to be an issue with the symmetric preconditioned M* operator.  I'll fill in the missing pieces and get this pushed shortly.

**Comment by AlexVaq** [comment] 2017-04-19 13:47
Thanks Kate, I appreciate that you found the time to do this.

**Comment by maddyscientist** [comment] 2017-04-19 19:54
@AlexVaq I fixed this and pushed it to the feature/rdma branch
(383a7c47c0f10112987ad3841fa02b7885737d7d), as well as fixing some other issues: added full solution_type support for non-degenerate twisted-mass fermions in invert_test, and fixed an apparent bug in the symmetric-preconditioned reference dslash dagger operator (98005c6e40c769553c698513e1f9a7ad9e576240 - does this fix make sense?).  I was going to push a simple hotfix, but the feature/rdma branch already fixes other issues for twisted mass so thought it best to put the fix there.  This branch does seem stable though, and I hope to get this merged soon into develop.  For developing the twisted-clover doublet code, it's probably a good idea to simply merge feature/rdma into your development branch.

**Closed** 2017-05-31 08:56 UTC
