### ISSUE TITLE
node freezing when I use 4 gpus in one box

### ISSUE THREAD

**Issue by kimjangho1120** [lattice/quda#669] opened 2018-01-03 15:38 UTC
Dear all,

In our cluster, there are 4 k80 cards.
When I run the tests/invert_test with 2 gpus, it works well.
However, if I increase the number of gpus larger than 4, node freezes.
My command is 
mpirun -np 4 ./invert_test --gridsize 1 1 2 2
Does anyone suffer this problem?

Best Regards,
Jangho Kim

**Comment by kimjangho1120** [comment] 2018-01-08 23:11
I solve the problem.
After I set "export QUDA_ENABLE_P2P=0" in .bashrc, it works.

**Comment by maddyscientist** [comment] 2018-01-09 14:04
Hi @kimjangho1120.  This is very unexpected behaviour, and I don't think I've seen this anywhere.  Sorry to hear you are having this issue.

* Can you confirm you are using the latest code from the `develop` branch?
* Can you share the output from nvidia-smi?
* What version of CUDA and GCC are you using?
* If you have an Intel CPU on your system, can you confirm that ACS is disabled (see https://devtalk.nvidia.com/default/topic/883054/multi-gpu-peer-to-peer-access-failing-on-tesla-k80- for more details)

Thanks

**Comment by kimjangho1120** [comment] 2018-01-09 14:28
I use develop branch of quda.

nvidia-smi output is
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:0A:00.0 Off |                  Off |
| N/A   21C    P8    26W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:0B:00.0 Off |                  Off |
| N/A   23C    P8    31W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:0E:00.0 Off |                  Off |
| N/A   17C    P8    27W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:0F:00.0 Off |                  Off |
| N/A   22C    P8    30W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           On   | 00000000:8A:00.0 Off |                  Off |
| N/A   25C    P8    26W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           On   | 00000000:8B:00.0 Off |                  Off |
| N/A   21C    P8    29W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           On   | 00000000:8F:00.0 Off |                  Off |
| N/A   25C    P8    27W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           On   | 00000000:90:00.0 Off |                  Off |
| N/A   24C    P8    30W / 149W |      0MiB / 12205MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

I use following modules.
module load GNU/4.8.2 OpenMPI/1.6.5 CUDA/8.0 CMake/3.7.2
When I try CUDA/7.5 and CUDA/9.0, there were same problems.

The output of lspci | grep -i plx is
06:00.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
07:04.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
07:08.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
07:0c.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
08:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
09:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
09:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
0c:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
0d:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
0d:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
86:00.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
87:04.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
87:08.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
87:0c.0 PCI bridge: PLX Technology, Inc. Device 8764 (rev ab)
88:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
89:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
89:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
8d:00.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
8e:08.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)
8e:10.0 PCI bridge: PLX Technology, Inc. PEX 8747 48-Lane, 5-Port PCI Express Gen 3 (8.0 GT/s) Switch (rev ca)

I think P2P communication is set as default. So if there are 2 gpus in a node, there is no problem. But more than 2 gpus, P2P communication should be turned off.

Thanks,
Jangho

**Comment by maddyscientist** [comment] 2018-01-09 14:33
Thanks @kimjangho1120.

Can you send the output `nvidia-smi topo -m`?

To check if ACS is enabled on your system, can you follow the instructions in https://devtalk.nvidia.com/default/topic/883054/multi-gpu-peer-to-peer-access-failing-on-tesla-k80-?  You will need root access to do this.

**Comment by maddyscientist** [comment] 2018-01-09 14:33
Also, if your motherboard is a SuperMicro, then this FAQ will help: https://www.supermicro.com/support/faqs/faq.cfm?faq=20732

**Comment by kimjangho1120** [comment] 2018-01-09 14:46
nvidia-smi topo -m is 
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	mlx5_0	CPU Affinity
GPU0	 X 	PIX	PXB	PXB	SYS	SYS	SYS	SYS	SYS	0-13
GPU1	PIX	 X 	PXB	PXB	SYS	SYS	SYS	SYS	SYS	0-13
GPU2	PXB	PXB	 X 	PIX	SYS	SYS	SYS	SYS	SYS	0-13
GPU3	PXB	PXB	PIX	 X 	SYS	SYS	SYS	SYS	SYS	0-13
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PXB	PXB	PHB	14-27
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PXB	PXB	PHB	14-27
GPU6	SYS	SYS	SYS	SYS	PXB	PXB	 X 	PIX	PHB	14-27
GPU7	SYS	SYS	SYS	SYS	PXB	PXB	PIX	 X 	PHB	14-27
mlx5_0	SYS	SYS	SYS	SYS	PHB	PHB	PHB	PHB	 X 	

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks

I am not admin, so I can not have root.
Thanks,
Jangho

**Comment by maddyscientist** [comment] 2019-02-28 05:59
Closing this issue, since it appeared to be a system configuration issue that we can't do anything about in QUDA.  @kimjangho1120 feel free to reopen the issue if you think there's anything for us to do here.

**Closed by maddyscientist** 2019-02-28 05:59 UTC
