### ISSUE TITLE
Performance of plaquette computation

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#311] opened 2015-07-08 17:03 UTC
Preliminary tests of the performance of the plaquette code merged in #307 show possible performance issues. Once we merge the vectorized accessor from @nmrcardoso (pull request #253) we should re-evaluate the performance.

**Comment by mikeaclark** [comment] 2015-08-03 06:43
I noticed that the plaquette algorithm doesn't use shared-memory tuning.  Enabling this improves the performance up to 1.3x on sm_30.  I'll rerun this on sm_35/sm_52 GPUs to see what the improvement is on large GPUs.

**Comment by mikeaclark** [comment] 2015-08-03 06:46
This has been enabled with de557e2f3e2bfc4b8216c3caace783e29bff564b.

**Comment by nmrcardoso** [comment] 2015-08-04 16:07
@mikeaclark , probably I should enable also this in the gauge fixing code, heatbath and det/trace codes.
I also noticed that in the plaquette you use the 2D block reduction, I didn't knew that this was implemented in CUB.
I tried to implement this and it seems that the CUB code in the develop branch is outdated to support the 2D block reduction.
I only tested this in pgauge_det_trace.cu, but didn't noticed any performance in K40X.

I think you have a typo in this plaquette code, since the reduction is in a 2D block,
the attomicAdd updates shouldn't be done only for threadIdx.x == 0 && threadIdx.y == 0,
i.e. for the first thread in the 2D block ?

**Comment by mikeaclark** [comment] 2015-08-04 16:32
2-d block reductions require a new version of cub, that's why I've updated cub in the hotfix/cub-update branch.  I'll make a pull for this shortly, once I've finished some more investigations.

You're correct that my code did have a bug, though I'd already caught it in my local copy :)

I'll report back on this bug once I've formed some conclusions on how to make the gauge code go faster.  You should definitely try switching on shared-memory tuning in the gauge-fixing routines though, as I noticed a speed boost with this for the plaquette, and I assume similar would be seen for the gauge fixing routines.

The performance limiter for the 8-reconstruct, and to a lesser degree the 12-reconstruct is because of two factors
* Register spilling caused by dynamic indexing into the `dx` array
* Too many registers being used which leads to poor occupancy.

While in principle the `dx` array indexing can be known at compile time, this requires that the `mu`/`nu` loops are fully unrolled.  Doing so makes the register explosion even worse.

**Comment by mikeaclark** [comment] 2015-08-04 20:25
I found a major issue with the reconstruct 8 gauge accessor in single/half precision.  That being that in the unpack operation the double precision sqrt was being invoked and not the single precision one.  This causes unnecessary slow double-precision instructions as well as an explosion in register count.  This is fixed with commit 8515b987b1e6051999588ea3b7b861ea5cb3a185.

**Comment by mikeaclark** [comment] 2015-08-04 20:54
I think I'm ready to sign off on this for now.  Here's a performance comparison of the present release/0.7.x branch with the latest improvements in d528e269a4f676ad61ee66f60116f03b484df42d (vectorized gauge-field accessor, reconstruct-8 unpack improvement in single/half precision, keep parity in the thread block to increase locality, shared-memory tuning).

K80 (using one GPU)
* reconstruct 18
  * old 160 GFLOPS => new 267 GFLOPS
* reconstruct 12
  * old 127 GFLOPS => new 224 GFLOPS
* reconstruct 8
  * old 107 GFLOPS => new 166 GFLOPS

M6000 (using one GPU)
* reconstruct 18
  * old 271 GFLOPS => new 417 GFLOPS
* reconstruct 12
  * old 249 GFLOPS => new 328 GFLOPS
* reconstruct 8
  * old 130 GFLOPS => new 254 GFLOPS

The performance still isn't perfect, but it's a lot better than it was.  There is still the problem related to register spilling with the `dx` array and overall high latency.  A lot of cycles are spent on the atomic summation: the next avenue for improvement would be to replace the atomic double accumulation with a reduction using the last active CTA.  This will also have the advantage of making the results reproducible once tuning has completed.  We can track that in a future issue though.

**Closed** 2015-08-04 20:54 UTC
Labels: optimization

**Comment by mikeaclark** [comment] 2015-08-10 23:25
As of c94a92b05ea3f5f8543610a56cba376587f25404, the call to `atomicAdd(double*, double)` has been replaced with a last-CTA reduction approach (as used in reduce_core.h).  New performance for the plaquette running on one M6000 in single precision (this include further performance fixes for single precision reconstruct 8 accessors - 0f80c8eeed9d906a5fa45b08ba3d32300d65aa70)

M6000 (using one GPU)
* reconstruct 18  
  * 893 GFLOPS
* reconstruct 12 
  * 1078 GFLOPS
* reconstruct 8 
  * 1187 GFLOPS

**Comment by mathiaswagner** [comment] 2015-08-11 00:05
Any idea about Kepler performance?

**Comment by mikeaclark** [comment] 2015-08-11 00:06
I haven't tested it yet, as I've got no Kepler in my workstation.
