### ISSUE TITLE
verify() fails in some cases in feature/multigrid

### ISSUE THREAD

**Issue by weinbe2** [lattice/quda#657] opened 2017-11-08 00:05 UTC
In some cases, the call to verify() as a part of the coarse construct in multigrid now fails. It fails at the check "0 = (1 - P P^\dagger) v_k"  in the cases I've been able to produce in the current feature/multigrid. I can also get it to fail at the comparison between the constructed and emulated coarse op with some combinations of operator, partitions, and blocksize in feature/multigrid-circlestag (since I have some more Nc's templated over), which makes me think the issue is in the construction of the transfer operator.

Some examples that trigger the issue:

`./multigrid_invert_test --prec double --prec-sloppy single --mg-levels 3 --mg-block-size 0 3 3 3 2 --mg-block-size 1 2 2 2 2 --solve-type direct-pc --dslash-type wilson --device 0 --mg-nvec 0 24 --mg-nvec 1 32 --mass 0.00001 --mg-coarse-solver-maxiter 1 100 --mg-coarse-solver-maxiter 2 100`

Output around error:

`MG level 2 (GPU): Checking 0 = (1 - P P^\dagger) v_k for 32 vectors`
`MG level 2 (GPU): Vector 0: norms v_k = 1.000000e+00 P^\dagger v_k = 1.000000e+00 P P^\dagger v_k = 1.000000e+00`
`MG level 2 (GPU): L2 relative deviation = 3.785223e-04`
`MG level 2 (GPU): ERROR: failed (rank 0, host nvsocal2, /scratch/weinbe2/quda-2017-11-07-standardmg/quda/lib/multigrid.cpp:439 in verify())`
`MG level 2 (GPU):        last kernel called was (name=N4quda4blas5Norm2Id6float2S2_EE,volume=8x8x8x12,aux=vol=6144,stride=3072,precision=4,Ns=2,Nc=24)`

---

With emulated multi-GPU:

`./multigrid_invert_test --prec double --prec-sloppy single --mg-levels 3 --mg-block-size 0 3 3 3 2 --mg-block-size 1 2 2 2 2 --solve-type direct-pc --dslash-type wilson --device 0 --mg-nvec 0 24 --mg-nvec 1 32 --mass 0.00001 --mg-coarse-solver-maxiter 1 100 --mg-coarse-solver-maxiter 2 100 --partition 8`

Output around error:

`MG level 2 (GPU): Checking 0 = (1 - P P^\dagger) v_k for 32 vectors`
`MG level 2 (GPU): Vector 0: norms v_k = 1.000000e+00 P^\dagger v_k = 1.000000e+00 P P^\dagger v_k = 1.000000e+00`
`MG level 2 (GPU): L2 relative deviation = 1.294210e-04`
`MG level 2 (GPU): ERROR: failed (rank 0, host nvsocal2, /scratch/weinbe2/quda-2017-11-07-standardmg/quda/lib/multigrid.cpp:439 in verify())`
`MG level 2 (GPU):        last kernel called was (name=N4quda4blas5Norm2Id6float2S2_EE,volume=8x8x8x12,aux=vol=6144,stride=3072,precision=4,Ns=2,Nc=24)`

---

Changing the block size, for ex, `--mg-block-size 0 2 2 2 2`, caused the same issue (with different L2 relative deviations, of course).

**Comment by maddyscientist** [comment] 2017-11-08 00:53
Ok, I have reproduced the problem with the supplied line.  The fact that it fails with and without partitioning shows us that the problem is not a parallelization problem.

However, I see that the level 2 null space refinement fails to converge on one of the vectors - not necessarily surprising since this is a small mass in free field theory.  Investigating to see if this is the cause of the failure in the block orthogonalization (if you give a bad vector to Gram Schmidt then it can fail to orthogonalize properly).  I suspect this is the issue here.

**Comment by maddyscientist** [comment] 2017-11-08 01:38
Closing this as not a bug.  The failure is occurring here because the quark mass is very low, and BiCGstab fails to produce a good set of null vectors on the intermediate grid.  This results in the block orthogonalization (which using Gram Schmidt) to fail to produce an orthogonal basis to the expected precision.  Any of the following makes the issue go away:
* Run at mass=0.0001 instead of mass=0.00001
* Use CG for finding nullspace vectors instead of BiCGStab (`--mg-setup-inv 0 cg --mg-setup-inv 1 cg`)
* Run the block orthogonalization routine twice

**Closed by maddyscientist** 2017-11-08 01:38 UTC
Labels: bug
