### ISSUE TITLE
QUDA develop build of lib/deflation.cpp throws compilation error from Eigen header

### ISSUE THREAD

**Issue by detar** [lattice/quda#701] opened 2018-06-11 20:09 UTC
In file included from /ccs/home/detar/quda/build-cmake-develop/externals/eigen/src/Eigen/Eigen/Core:376:
/ccs/home/detar/quda/build-cmake-develop/externals/eigen/src/Eigen/Eigen/src/Core/arch/AltiVec/PacketMath.h:1025:13: error: 
      cannot initialize a variable of type 'Packet2bl' (aka 'Packet2ul') with an
      rvalue of type '__vector __bool unsigned long long' (vector of 2
      'unsigned long long' values)
  ...mask = vec_cmpeq(reinterpret_cast<Packet2d>(select), reinterpret_cast<Packet2d>(p2l_ONE));
1 error generated.
Error while processing /ccs/home/detar/quda/lib/deflation.cpp.

Is there a way to turn off Eigen for now?  ccmake insisted on having it.

**Comment by maddyscientist** [comment] 2018-06-11 20:10
Hi @detar.  Which system is this coming from?

This looks like you are compiling with XLC, which Eigen doesn't support.  If this is the case, then switching to GCC instead of XLC will fix the issue.

**Comment by detar** [comment] 2018-06-11 20:14
Hi Kate,

Summit.  Indeed, it is xlC.  I'll try gcc/g++.

Thanks,

Carleton

**Comment by alexstrel** [comment] 2018-06-11 21:18
Hi Carleton, 
I had no issues with eigen-3.2.10 (and xlc++ 16.0.3) while the latest eigen, ver 3.3.4, gave me the same error , hope this will work for you.

**Comment by mathiaswagner** [comment] 2018-06-12 06:18
Do we need to add a warning to QUDA when xlc is detected? I guess a few people ran into this issue and I think cmake has everything that is needed to detect xlc.

**Comment by alexstrel** [comment] 2018-06-12 14:52
@mathiaswagner   a warning message would be helpful, since eigen is our default library.

**Comment by mathiaswagner** [comment] 2018-06-12 15:01
@alexstrel I don't have access to Summit. Do you mind putting

```
message(STATUS "CMAKE_CXX_COMPILER_ID ${CMAKE_CXX_COMPILER_ID}")
```

in the top level CMakeLists.txt (somewhere after the `project("QUDA" ...` line and verify that the output is `XL` ?

**Comment by alexstrel** [comment] 2018-06-12 15:22
@mathiaswagner  sure. BTW, I'm running on IBM Poughkeepsie Client Center that provides with a similar environment.

**Comment by alexstrel** [comment] 2018-06-12 16:29
@mathiaswagner here is the example (note that recent xlc adopted clang frontend):  
Currently Loaded Modules:
  1) cuda/9.2   2) xlc/16.1.0   3) smpi/10.1.1.0

cmake output :

-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /gpfs/gpfs_gl4_16mb/RHEL/XL/xlC/16.1.0/bin/cc
-- Check for working C compiler: /gpfs/gpfs_gl4_16mb/RHEL/XL/xlC/16.1.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /gpfs/gpfs_gl4_16mb/RHEL/XL/xlC/16.1.0/bin/xlc++
-- Check for working CXX compiler: /gpfs/gpfs_gl4_16mb/RHEL/XL/xlC/16.1.0/bin/xlc++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 
-- QUDA 0.9.0 (v0.9.0a1-with_v.0.8_milc_interface-209-ga04320c-dirty) **
-- cmake version: 3.6.3
-- Source location: /gpfs/gpfs_gl4_16mb/b7p319/b7p319ab/work/quda-hotfix
-- Build location: /gpfs/gpfs_gl4_16mb/b7p319/b7p319ab/work/quda-hotfix/build-hx
-- Build type: HOSTDEBUG
-- CMAKE_CXX_COMPILER_ID Clang
-- Building QUDA for GPU ARCH sm_70

**Comment by mathiaswagner** [comment] 2018-06-12 16:52
Hmm, `Clang` as compiler ID is not useful. Clang should work fine (although we have not tested QUDA with clang in a while. Should add this to Jenkins.
Do you know if Eigen compilation fails also with the clang frontend?

Is this the same version as on Summit?

**Comment by alexstrel** [comment] 2018-06-12 19:21
Unfortunately, clang is not exposed for users on IBM system. I need to compile my own version.  Also,  I have used clang-6.0.0 (and the latest Eigen) for QUDA compilation on my ubuntu desktop, without issues.

**Comment by detar** [comment] 2018-06-12 19:27
We are being booted off of Summit and our projects are being 
discontinued, pending acceptance testing, so I have stopped building 
code there for now.

**Comment by mathiaswagner** [comment] 2018-06-14 07:01
@trudeaun Ah, thanks for reminding me. I remember reading something in the release notes. Anyway, not sure this is a good solution unless everyone uses cmake 3.11 or later on Power systems. 
But instead of adding a warning in our build system we would  much more like to see a fix of the underlying issues in xlc so that eigen just works with it.

**Comment by maddyscientist** [comment] 2018-06-14 07:10
I have filed a bug at Eigen: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1555, let's see what they say.

**Comment by alexstrel** [comment] 2018-06-14 15:29
@maddyscientist thanks for the suggestion. After inspection of PacketMath.h from eigen-3.3.4,  the suggested  code snippet is already there. Macro ```EIGEN_COMP_CLANG``` is defined for XLC compiler , along with ```EIGEN_COMP_IBM``` macro . (So I extended  with an additional check for ```EIGEN_COMP_IBM```,  for consistency ).  The problem was with line 1025, namely I added a reinterpret cast to type Packet2bl: 
``` Packet2bl mask = reinterpret_cast<Packet2bl>( vec_cmpeq(reinterpret_cast<Packet2d>(select), reinterpret_cast<Packet2d>(p2l_ONE));``` 
With this modification I was able to compile the code.   I'm still curios why the problem was not detected with clang compiler.

**Comment by trudeaun** [comment] 2018-06-14 17:36
@mathiaswagner Hi Mathias, if you think there is an XLC compiler bug, can you please provide me with some reduced steps to reproduce? I see in the last comment that a code change might have fixed the issue.

```
PacketMath.h:1025:13: error:
cannot initialize a variable of type 'Packet2bl' (aka 'Packet2ul') with an
rvalue of type '__vector __bool unsigned long long' (vector of 2
'unsigned long long' values)
...mask = vec_cmpeq(reinterpret_cast(select), reinterpret_cast(p2l_ONE));
```
Did the following change in the code resolve the error above?
`Packet2bl mask = vec_cmpeq(reinterpret_cast(select), reinterpret_cast(p2l_ONE));`
->
`Packet2bl mask = reinterpret_cast<Packet2bl>( vec_cmpeq(reinterpret_cast<Packet2d>(select), reinterpret_cast<Packet2d>(p2l_ONE));`

**Comment by alexstrel** [comment] 2018-06-14 18:01
@trudeaun yes, this will fix the error. (It did in my case)
I think one may reproduce the error directly in the Eigen library, just try ```make blas``` or ```make check```

**Comment by c-e-bowler** [comment] 2018-06-20 12:39
I have been able to synthesize a short test, which I expect is representative of the Eigen diagnostic:

#include<altivec.h>

void foo(__vector double v) { 
  __vector bool long long r = vec_cmpeq(v, v); 
}

Clang and g++ accept this because they allow lax vector conversions while the XL compiler does not.  Clang emits a diagnostic as well if -fno-lax-vector-conversions is specified.  The return type differs from the result type of the function.  The diagnostic is valid and I would suggest the Eigen code be updated to improve portability.

**Comment by mathiaswagner** [comment] 2018-06-20 17:37
@c-e-bowler Sure, but I guess that is not a QUDA issue and you should add that to the bug that @maddyscientist filed (see above) http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1555

**Comment by trudeaun** [comment] 2018-06-20 21:42
@c-e-bowler I was able to get an account to post at http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1555, and have posted your comments. Thanks!

**Comment by trudeaun** [comment] 2018-06-21 16:15
The [fix has been applied](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1555#c4) to eigen v3.3:
>Gael Guennebaud 2018-06-21 08:30:06 UTC
>I applied the reinterpret_cast fix:
>https://bitbucket.org/eigen/eigen/commits/d2f8e1b572c0/ (default)
>https://bitbucket.org/eigen/eigen/commits/23eb37691f14/ (3.3)

**Comment by mathiaswagner** [comment] 2018-06-22 13:08
@alexstrel Do you mind trying that on the Power system you have access to?

I am inclined to stay on a released version of Eigen but we could switch to the fixed version for Power.

**Comment by alexstrel** [comment] 2018-06-22 15:39
@mathiaswagner  Unfortunately, it's not ready for the usage:  I found a missing close parenthesis in the updated version,
`
/gpfs/gpfs_gl4_16mb/b7p319/b7p319ab/install/eigen-devel/include/eigen3/Eigen/src/Core/arch/AltiVec/PacketMath.h:1057:131: error: expected ')'
  Packet2bl mask = reinterpret_cast<Packet2bl>( vec_cmpeq(reinterpret_cast<Packet2d>(select), reinterpret_cast<Packet2d>(p2l_ONE));
`                             

In addition, after fixing the typo, I got another error : 
`
/gpfs/gpfs_gl4_16mb/b7p319/b7p319ab/install/eigen-devel/include/eigen3/Eigen/src/Core/arch/AltiVec/PacketMath.h:945:71: error: 1540-0557 The
      asm operand does not match the specified constraint.
  __asm__ ("xvcmpgtdp %x0,%x2,%x1\n\txxsel %x0,%x1,%x2,%x0" : "=&wa" (ret) : "wa" (a), "wa" (b));
`    
I'll look into the issue later today.

**Comment by maddyscientist** [comment] 2018-06-25 20:46
@alexstrel can you try with this?
https://bitbucket.org/eigen/eigen/pull-requests/410/fix-typo-in-pblend-for-altivec/diff

**Comment by alexstrel** [comment] 2018-06-25 21:36
@maddyscientist the second issue is still there, I need to report: 
`
/gpfs/gpfs_gl4_16mb/b7p319/b7p319ab/install/eigen-devel-2/include/eigen3/Eigen/src/Core/arch/AltiVec/PacketMath.h:945:71: error: 1540-0557 The
      asm operand does not match the specified constraint.
  __asm__ ("xvcmpgtdp %x0,%x2,%x1\n\txxsel %x0,%x1,%x2,%x0" : "=&wa" (ret) : "wa" (a), "wa" (b));
`

**Comment by maddyscientist** [comment] 2018-06-25 21:42
@alexstrel Thanks for checking @alexstrel.  It seems that the patch works fine on latest release of Eigen, but the issue you are seeing is only on latest HEAD version from BitBucket.  I've added your latest bug report on http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1555....

**Comment by trudeaun** [comment] 2018-06-27 17:59
@alexstrel Do you know where the `__asm__` inline assembly call is coming from in the error message? Line 945 is the macro `EIGEN_DEBUG_ALIGNED_STORE`, defined to be empty. Are you able to compile with `-P` to create preprocessed .i files? Do you know which altivec.h is being picked up? Is it the XL one, or something different?

**Comment by mathiaswagner** [comment] 2019-06-14 12:19
Is this still an issue? If yes please reopen.

**Closed by mathiaswagner** 2019-06-14 12:19 UTC
