### ISSUE TITLE
can't  [rp[er;u launch mpi jobs on SummitDev

### ISSUE THREAD

**Issue by stevengottlieb** [lattice/quda#606] opened 2017-04-03 20:12 UTC
I have run some single GPU jobs on SummitDev, but am having trouble trying to run multiGPU jobs.  I am launching with this command:
mpirun -gpu --map-by ppr:1:socket ./su3_rhmd_hisq_noFF.mpi 
or without any --map-by argument.  In either case, this shows up in the output.  Looks like both MPI ranks are trying to attach to same GPU.

QUDA 0.9.0 (git v0.8.0-1620-g3f2f3a7-sm_60)
QUDA 0.9.0 (git v0.8.0-1620-g3f2f3a7-sm_60)
Found device 0: Tesla P100-SXM2-16GB
Found device 0: Tesla P100-SXM2-16GB
Found device 1: Tesla P100-SXM2-16GB
Found device 1: Tesla P100-SXM2-16GB
Found device 2: Tesla P100-SXM2-16GB
Found device 2: Tesla P100-SXM2-16GB
Found device 3: Tesla P100-SXM2-16GB
Found device 3: Tesla P100-SXM2-16GB
Using device 0: Tesla P100-SXM2-16GB
Using device 0: Tesla P100-SXM2-16GB
WARNING: Data reordering done on GPU (set with QUDA_REORDER_LOCATION=GPU/CPU)
ERROR: (CUDA) all CUDA-capable devices are busy or unavailable (/ccs/home/gottlieb/quda/lib/
interface_quda.cpp:485 in initQudaMemory())
       last kernel called was (name=,volume=,aux=)

Hope there is an easy fix.
Steve

**Comment by maddyscientist** [comment] 2017-04-10 19:05
@stevengottlieb Is this issue still a problem on SummitDev?  Can you test the QUDA internal packages, e.g., tests/staggered_invert_test, test/staggered_dslash_test, etc., to see if they have the same issue?

What's confusing about the message there is that QUDA is reporting some information that's only reported by process 0.  Is this defintiely a multi-GPU build of QUDA: this behaiour would be triggered by trying to run multiple copies of a serial build of QUDA.

**Comment by kostrzewa** [comment] 2017-04-10 19:10
Or, possibly, by using a different MPI launcher than the application was compiled with. (had that happen once or twice in incompatible MPICH / MVAPICH mixups)

**Comment by maddyscientist** [comment] 2017-04-11 19:59
@stevengottlieb, together with @bjoo, we've made some progress on this issue.  Long story short: if you've been building QUDA build enabled, then we have fixed the issue (use feature/rdma branch -
 I've just pushed the fix there).  

The problem was that the SummitDev defaults to running in compute exclusive mode which means that different processes cannot share the same GPU.  This normally isn't a problem, as in QUDA each process only allocates a context on the GPU it is running on.  However, if QUDA was built in debug mode, then there all processes were trying to create a GPU context on GPU 0, due to a misplaced cudaDeviceSynchronize() call in the communications initialization.

**Comment by stevengottlieb** [comment] 2017-04-15 21:10
@maddyscientist, Sorry for being confusing before and for not reading
all my email this week.

First, about NCSA, there is an Innovative System Lab there and they let
me have an account on a cluster that single and quad P100 systems.  That
is where I first was able to run on P100 hardware and where I ran the
hotfix/hisq_link (as best I recall).  I was able to run on multiple GPUs
there.

I looked for the feature/rdma branch and did not find it.  Used 
git branch -a
Has that been absorbed into develop?

As far as I know, I have not been using debug mode.

**Comment by maddyscientist** [comment] 2017-04-15 22:52
No worries @stevengottlieb 😄 

To see the feature/rdma branch, you probably just need to update your local repository: `git remote update`.  I need to do more testing on this branch before it is merged into develop, but it currently passes all tests that I can think of.

So, am I correct in thinking that all your issues then are on SummitDev and not on the P100 system at NCSA?

**Comment by stevengottlieb** [comment] 2017-04-16 01:42
Yes, @maddyscientist, all my issues are on SummitDev, but I have new
information.  Mnetioned before that I was going to try QUDA 0.8.x on
SummitDev.  I built that version and relinked MILC to it.  I submitted
some 2 GPU benchmarks before leaving for a movie and just got back.  I
look at the end of one output file and it looked like normal
termination.  I just submitted a 4 GPU run on a single node.  I will
then try some runs on multiple nodes.

This makes me wonder about current dev branch.  I will work harder on
finding the rdma branch.

Thanks!

**Comment by maddyscientist** [comment] 2017-04-16 01:50
Thanks for the new information.  There are many difference between devel and 0.8.x, so it's hard to pin down what the difference could be caused by.  One issue that did trip me up on POWER was the differing conventions of char variables being unsigned on POWER versus being signed on x86.  While I think I fixed that problem, I do wonder if there are other differences between POWER and x86 that have been causing some of the issues that yourself and @bjoo have been having on SummitDev.  Having said that, I have run the devel branch with MILC on Minsky nodes before and had no issues at all.

One thing to try with a devel build is to try disabling peer-to-peer access.  (set the envarg `QUDA_ENABLE_P2P=0`).

The feature/rdma branch improves the handling of multi-process dslash massively, not just in performance, but also in low-level benchmarking and debugging.  I'll get a wiki page written about this shortly describing this.

**Comment by maddyscientist** [comment] 2017-04-26 07:12
@stevengottlieb Any updates from trying feature/rdma on SummitDev?  I've continued to improve this branch's robustness, catching all corner cases that I can think of.  At least on Piz Daint and the SaturnV clusters, I can't find any configuration that is breaking (MILC and QUDA multigrid both seem to be working fine).  If you're still having problems, can you pull the latest version of feature/rdma?

**Comment by maddyscientist** [comment] 2017-05-06 18:29
Closing this issue, as @stevengottlieb confirmed this issue reported at the top of this issue was not a QUDA problem.  

Note that when running on SummitDev, QUDA was hanging: this has been root caused to Spectrum MPI that is installed on SummitDev.  The cure for this hang is to use a different MPI library - @bjoo has successfully testing Chroma + QUDA, both BiCGStab and Multigrid, with OpenMPI 2.1.0 with the feature/rdma branch, and everything appears to be working fine.

**Closed by maddyscientist** 2017-05-06 18:29 UTC
